name: Linting (Improved)

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]
  workflow_dispatch:
  workflow_call:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go with linting tools
        uses: ./.github/actions/setup-go
        with:
          go-version: '1.23'
          install-lint: 'true'

      - name: Run golangci-lint
        run: golangci-lint run --timeout=5m

      - name: Run go vet
        run: go vet ./...

      - name: Check for unused dependencies
        run: |
          go mod tidy
          if [ -n "$(git status --porcelain go.mod go.sum)" ]; then
            echo "Dependencies are not tidy. Please run 'go mod tidy'"
            git diff go.mod go.sum
            exit 1
          fi

      - name: Check for security vulnerabilities
        run: |
          go install golang.org/x/vuln/cmd/govulncheck@latest
          govulncheck ./...
